### ISSUE TITLE
Error when compiling project

### ISSUE THREAD

**Issue by galli-leo** [lion03/KinectDemoRoom#1]
I have the following error when trying to compile the project of any branch against 4.9.2:

`EXEC : error : Couldn't find parent type for 'K2Node_AsyncAction' named 'UK2Node_BaseAsyncTask' in current module or any other module parsed so far.`

I think this has something to do with the right module not loading. I allready have tried adding the 2 modules for K2Node_asynAction "Kismet" and BaseAsyncTask "BlueprintGraph". No luck.

**Comment by galli-leo** [comment]
Fixed it. Added this to the KinectV2Module:

`PrivateDependencyModuleNames.AddRange(
       new string[]
       {
           // ... add private dependencies that you statically link with here ...
           "Core",
           "CoreUObject",
           "InputCore",
           "Slate",
           "Engine",
           "AssetTools",
           "UnrealEd", // for FAssetEditorManager
           "KismetWidgets",
           "KismetCompiler",
           "BlueprintGraph",
           "GraphEditor",
           "Kismet",  // for FWorkflowCentricApplication
           "PropertyEditor",
           "EditorStyle",
           "Slate",
           "SlateCore",
           "Sequencer",
           "DetailCustomizations",
           "Settings",
           "RenderCore",
       }
   );`

**Comment by muchcharles** [comment]
Hey, the line endings got messed up in your post, can you paste again? Are any of the entries commented out?  I'm assuming it is supposed to be like this?

`PrivateDependencyModuleNames.AddRange( new string[] {
// ... add private dependencies that you statically link with here ...
"Core", "CoreUObject", "InputCore", "Slate", "Engine", "AssetTools", "UnrealEd",
// for FAssetEditorManager
"KismetWidgets", "KismetCompiler", "BlueprintGraph", "GraphEditor", "Kismet",
// for FWorkflowCentricApplication
"PropertyEditor", "EditorStyle", "Slate", "SlateCore", "Sequencer", "DetailCustomizations", "Settings", "RenderCore", } );`

Is that right, or were any of them supposed to be commented?  Why the dependency on Sequencer?

**Comment by galli-leo** [comment]
@muchcharles Kinda long since I touched that project, so IDK. But check my project out here: https://github.com/galli-leo/VirtualWardrobe/blob/master/MagicMirror/Plugins/KinectV2/Source/KinectV2/KinectV2.Build.cs. I think this should work.

**Comment by muchcharles** [comment]
Thanks!
